name: perf_test
description: A set of classes to run performance tests
version: 0.1.0
homepage: https://github.com/aiurovet/perf_test/

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  intl: ^0.17.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
