name: perf_test
description: A set of classes to run performance test(s) and compare results against the first test
version: 0.2.5
homepage: https://aiurovet.com/
repository: https://github.com/aiurovet/perf_test/

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies: 
  intl: ^0.19.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.16.0
