name: perf_test
description: A set of classes to run performance test(s) and compare results against the first test
version: 0.2.2
homepage: https://aiurovet.blogspot.com/

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  intl: ^0.17.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
